### PR TITLE
Readme and .gitignore

### PR DESCRIPTION
**Pull request by scrasmussen**
Edited the formatting of the Readme and added a .gitignore.

### CODE REVIEW

**Comment by zbeekman** [comment]
LGTM

But, I haven't read the README changes in detail.


also, a rename to README.md would be great, along with some minimal markdown formatting


ie

```markdown
H1
==

H1 text paragraphs....

H2
--

Talk about long integers or other config options

[linked text]


[linked text]: http://www.example.com
```

to produce:

---

H1
==

H1 text paragraphs....

H2
--

Talk about long integers or other config options

[linked text]


[linked text]: http://www.example.com

**Comment by scrasmussen** [comment]
Thanks @zbeekman for the recommendation. The changes to the README were just to formatting so the markdown definitely helps improve the look.

**Comment by zbeekman** [comment]
@scrasmussen do you have PSBLAS commit rights?

I'm wondering if it would be helpful if I approved your PR or if I should let Salvatore do it. I can't think of any reason why Salvatore would ever object to these changes.

**Comment by sfilippone** [comment]
@zbeekman you're almost right: there is nothing I disagree with in principle, but there is a small mistake which is actually my own: I changed the Makefile to put modules under /path/modules, whereas /path/include now contains Make.inc and the include files for the experimental C interface. 
Agree with everything else if @scrasmussen fixes this (and  I think he has commit rights)
Thanks
Salvatore

**Pull request merged**
