### PR TITLE
WIP: Add cmake scripts

### PR DESCRIPTION
**Pull request by zbeekman**
Hi Salvatore!

Here is a pull request to start the discussion regarding integrating a CMake build system into PSBLAS3.

## Changes made:

- [X] Renamed base/modules/{aux => auxil} for Windoze support (Really windows? I can't name a directory aux?!?!?! FFS)
- [X] Added CMake build scripts
- [X] Compile static or shared libraries based on whether `-DBUILD_SHARED_LIBS` is passed to CMake (CMake canonical convention)
- [X] Publicize build directory so that other packages can just do `find_package(psblas)` and get compiled targets in the build directory

## Outstanding work:

- [ ] Build all possible tests. Only the `hello` and `pingpong` tests are currently built. I/we need some guidance on how and when to build the other tests
- [ ] C bindings are not currently being built
- [ ] FC and CC still need to be set to the MPI compiler wrappers because we haven't fully implemented the use of [CMake's `FindMPI` module](https://cmake.org/cmake/help/v3.10/module/FindMPI.html).
- [ ] Install things to the same end location as the Autotools build
- [ ] Appropriate system introspection is missing

### CODE REVIEW

**Comment by zbeekman** [comment]
CC: @rouson

**Comment by sfilippone** [comment]
Hi @zbeekman 
I am back in Cranfield on Friday, will take a deeper look then. Development is  not active right now, so it should not be a problem. 
We need to have a  longer chat on how to handle the other tests. 
S.

**Comment by sfilippone** [comment]
Hi @zbeekman I have merged the template, and have tested this version with configure/make/install and building mld2p4-2 against it. I have *not* tested the cmake machinery, I suppose you did that?

**Comment by zbeekman** [comment]
Hi @sfilippone this is still a work in progress. I am getting close and hope to have a finished version for you to test later today. The CMake machinery appears to be working but requires a few more tweaks and changes.

**Comment by sfilippone** [comment]
@zbeekman  Ok, stainding by. Actually am very busy with classes, so I won't get back to this until weekend.

**Comment by sfilippone** [comment]
@zbeekman  Be aware that I made a simple change to the copyright statements, but by its nature it is a bit intrusive.

**Pull request closed without merging**
